Tests return code fixed
Change-Id: Iea4681e0a09ca883e03782e9ebc8bc7f5891413a

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -12,3 +12,7 @@ export TESTLOG ?= tests.log
 tests:
 	@rm -f $(TESTLOG) 
 	@cd tests; $(MAKE) tests
+	@if [ -n "$$(grep '\[FAILED\]' $$TESTLOG)" ]; then \
+		echo "One or more tests failed"; \
+		exit 1; \
+	fi
